### ISSUE TITLE
关于吞吐量的问题

### ISSUE THREAD

**Issue by jiangth122** [xtaci/kcp-go#104]
我在server和client都在本机做测试，发现通过SetWriteDelay、SetWindowSize、SetACKNoDelay、SetNoDelay调整参数，当吞吐量达到80-90MB/s后就没办法往上提升了，而tcp或者原始udp都可以达到300MB/s，是kcp-go最大只能支持这么大，还是我的配置不对呢？

**Comment by xtaci** [comment]
sendto()/recvfrom()的极限大概就是在180MB/s左右，你在本机测试，速度有一半开销没算到，就是recv()的开销，所以90MB/s x2 刚好就是180MB/s， 和我的测试结果一致。

**Comment by xtaci** [comment]
tcp是另一回事，tcp可以直接write一个很大的数据到内核，比如write 1MB buffer, 大大降低了syscall的头部开销。

**Comment by jiangth122** [comment]
理解你的意思，大包和小包的吞吐量确实不一样的，不过用kcp-go和原生udp对比测试，差距也是比较大的。

**Comment by xtaci** [comment]
原生udp的测试方法不需要保证udp writeTo的时候没有返回错误，内核没有丢包，这类问题，测试方法很重要。

**Comment by jiangth122** [comment]
好的，明白了，谢谢！！！我测试quic也是上不去，而且更糟糕，可能是我用的不对吧，我把测试的结果发出来，然后关闭这个问题吧！
![catch](https://user-images.githubusercontent.com/42835884/48332030-583d7500-e68d-11e8-87ff-fb788778dddc.jpg)
![catch2c5a](https://user-images.githubusercontent.com/42835884/48332032-58d60b80-e68d-11e8-8317-e9dfc4fa2dbd.jpg)
![catch238b](https://user-images.githubusercontent.com/42835884/48332034-58d60b80-e68d-11e8-97e6-04afe388114b.jpg)
![catch967e](https://user-images.githubusercontent.com/42835884/48332036-596ea200-e68d-11e8-894f-a89790bf3980.jpg)
