### ISSUE TITLE
为什么比较 segment.rto 和 current 的大小？

### ISSUE THREAD

**Issue by gitbufenshuo** [xtaci/kcp-go#106]
https://github.com/xtaci/kcp-go/blob/263526eb6dcb37c5b452e666f09bf077940878f7/kcp.go#L801

是不是应该比较 segment.resendts 和 current:
`if rto := _itimediff(segment.resendts, current); rto > 0 && rto < minrto {`

**Comment by xtaci** [comment]
fixed
