### ISSUE TITLE
什么时候支持SIP003

### ISSUE THREAD

**Issue by alexlee728** [xtaci/kcp-go#107]
@xtaci 什么时候能支持SIP003?

**Comment by xtaci** [comment]
what is SIP003?

**Comment by alexlee728** [comment]
> what is SIP003?

是一种协议。

@xtaci 

https://github.com/shadowsocks/kcptun

shadowsocks都遵循了SIP003协议的plugin。目前只能使用shadowsocks作者的kcptun版本，但是shadowsocks作者版本太低太低。还是希望kcptun原生支持。

现在很多人电脑和手机用的kcptun都是shadowsocks作者的，还是2017.09的。
