### ISSUE TITLE
这里是不是缺少kcp.shrink_buf()

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#109]
https://github.com/xtaci/kcp-go/blob/46244179af43531926030233f5662b137367ca84/kcp.go#L543

感觉这里需要kcp.shrink_buf()

**Comment by xtaci** [comment]
不需要，只需要una进行shrink_buf

**Comment by xtaci** [comment]
ack包也含有una的，没有必要在这里shrink

**Comment by l42111996** [comment]
想明白了
