### ISSUE TITLE
完全自定义的加密方式

### ISSUE THREAD

**Issue by v2ray** [xtaci/kcp-go#11]
目前 UDPSession 在构造的时候接受一个 cipher.Block 参数，然后用它对 UDP 数据加密。能否把这个参数扩展为一个自定义的类型，比如

```go
type Payload []byte

type Cryptor interface {
  Encrypt(Payload, Payload)
  Decrypt(Payload, Payload)
```

这样的话，kcp-go 的核心代码可以不必依赖于某种特定的加密方式。

**Comment by xtaci** [comment]
@v2ray 有点难度，在kcp里面，对数据的分段，是内部进行的，比如送入一个Payload []byte，可能被分割为很多个MTU大小的 UDP数据包发送，每个数据包都是独立加密封装的。

其次，kcp为了做整个数据包加密，包括数据＋KCP协议头(特别是协议头），只能在内部最终sendto之前完成加密，如果在外部做，kcp协议头只能是明文了，有安全风险。

所以这样的接口定义不合适，另外，目前的kcp-go使用的cipher.Block已经不依赖于某种特定的加密算法了， 常用算法都可以方便使用这个接口，包括salsa等，实现adapter可以做转换。

**Comment by xtaci** [comment]
@v2ray 你说的意思，是不是把encrypt()/decrypt()函数描述的CFB模式，改为外部自定义？

**Comment by v2ray** [comment]
是你说的第二种方式。

我想说的只是耦合的问题，加密解密和 session 没有直接关系，你可以把现有的 encrypt()/decrypt() 做成一个比如 DefaultCryptor，普通用户依赖可以通过简单的调用实现默认的加密方式，而高级用户可以更自由地定义加密和解密的方式。

**Comment by xtaci** [comment]
@v2ray 我试一下

**Comment by xtaci** [comment]
@v2ray 实现了一个 BlockCrypt接口，看下是不是你需要的

**Comment by v2ray** [comment]
谢谢，正是我想要的。

**Comment by testcaoy7** [comment]
但愿自定义加密早日能成为现实，建议加入基于公钥的加密方式
