### ISSUE TITLE
support ipv6?

### ISSUE THREAD

**Issue by yanchuang12** [xtaci/kcp-go#110]
ipv6.NewConn(nc).SetTrafficClass(dscp) can support ipv4/ipv6 ?
I want kcptun server to install only ipv4 , only ipv6 or ipv4 and ipv6. the server should monitor v4 packet and v6 packet. if recevied v4 packet create v4 session. if received v6 packet create v6 session. I think it is .  can you tell me better method. thanks~

**Comment by xtaci** [comment]
if you listen to an ipv4 address, the session is an ipv4 session;
and if you connect to an ipv6 address:port, the session is an ipv6 session;

**Comment by yanchuang12** [comment]
for example, the server support ipv4 and ipv6. kcptun server config listen all addr both ipv4 and ipv6. can the ipv4 client can connect kcptun ipv4 addr and the ipv6 client also can connect kcptun ipv6. two client  connect the same server, using different trans protocol

**Comment by xtaci** [comment]
no, it depends on which type of address you are listening on

**Comment by yanchuang12** [comment]
I am seting the server listen all available ip address， including ipv4 and ipv6. what will happen

**Comment by xtaci** [comment]
if ipv6 is enabled in your system,   the default address will be an ipv6 address

**Comment by yanchuang12** [comment]
kcptun isn't better seting support dual-stack?  this can more universal。As you say，for ipv4/ipv6 system， kcptun server only support ipv6 protocol。 ipv4 still accounts for the majority。

**Comment by xtaci** [comment]
of course kcptun server supports ipv4, just listen "0.0.0.0:port"

**Comment by xtaci** [comment]
I mean ,if you don't specify address, like  -l ":12948", this system will choose by itself

**Comment by xtaci** [comment]
kcptun is always **dualstack**,  the only problem is -dscp value has to be decides by yourselves, since   nobody knows whether the upper route will convert this to ipv6 or not.

**Comment by yanchuang12** [comment]
I know， thanks for explaining
