### ISSUE TITLE
mtu设置感觉有问题

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#114]
https://github.com/xtaci/kcp-go/blob/4149bfc8edcaa2bf68d9269dacd37c4031509155/sess.go#L149

mtu已经减去了headerSize
reserveBytes()计算mss的时候又会减去一次 headerSize,这里重复减去了headerSize

感觉这里mtu不应该减去headerSize

**Comment by xtaci** [comment]
对的 忘了这一行 但目前不影响kcptun ，SetMTU改了

**Comment by l42111996** [comment]
我只看kcp的实现 发现这里有些问题
