### ISSUE TITLE
用户数据过大

### ISSUE THREAD

**Issue by haozibi** [xtaci/kcp-go#116]
你好，

已知：使用 kcp-go 发送一个过大的包（超过 udp 包最大字节数），kcp-go 会把包分片，分成多个 udp 包发到服务端

问题 1：是不是就需要服务端读取多个分片手动恢复成最初的原始包，kcp-go并没有这一层面的支持？
问题 2：对于多协程发送过大的包到服务端，服务端就会同时收到多个所属不同包的分片，是否有什么技巧可以帮助恢复多个包？
问题 3：是不是可以把 kcp 透明，把它当成可靠的 udp 使用即可？

刚开始使用 udp，见谅

**Comment by biotooff** [comment]
maybe you need this
[https://github.com/xtaci/smux](url)

**Comment by jimmy9065** [comment]
1.kcp本身支持一个包分成255片，这个是kcp完成分包和组包的，再大就要在应用层做分包和组包了。
2.在应用层分包组包就是你问题2的答案了。你可以给包打上标记（比如时间戳和会话ID还有大分片ID），在接收端根据标记，根据分片ID重新组包。
3.kcp比普通的UDP做的还是多了点。如果只是要reliable的udp，你带个应答就可以了。

对kcp的理解你可以看[这个](https://github.com/skywind3000/kcp)
另外这个go-kcp, 至少上次看的时候，sess中，他把kcp的分片给bypass了。

**Comment by haozibi** [comment]
> 1.kcp本身支持一个包分成255片，这个是kcp完成分包和组包的，再大就要在应用层做分包和组包了。
> 2.在应用层分包组包就是你问题2的答案了。你可以给包打上标记（比如时间戳和会话ID还有大分片ID），在接收端根据标记，根据分片ID重新组包。
> 3.kcp比普通的UDP做的还是多了点。如果只是要reliable的udp，你带个应答就可以了。
> 
> 对kcp的理解你可以看[这个](https://github.com/skywind3000/kcp)
> 另外这个go-kcp, 至少上次看的时候，sess中，他把kcp的分片给bypass了。

**Comment by haozibi** [comment]
> maybe you need this
> [https://github.com/xtaci/smux](url)

I will read it, thx

**Comment by haozibi** [comment]
https://github.com/xtaci/kcp-go/blob/381f54c9f35e04dc46c6b7df4031eab7de1dfd95/sess.go#L256-L267 

此处把调用 `s.kcp.Send()` 数据包的大小限定为 小于等于` s.kcp.mss` 
https://github.com/xtaci/kcp-go/blob/381f54c9f35e04dc46c6b7df4031eab7de1dfd95/kcp.go#L326-L356
这就使 kcp 每次都是发送单个包，而没有用到 kcp 的拆包和分包。

是有什么考虑么？@xtaci

**Comment by xtaci** [comment]
不能用kcp的分包，你Write(1GB []byte)就超过255分片了

**Comment by xtaci** [comment]
你要做成消息，很简单啊， 消息封装为： |32bit data size |..... data ......|， 这样就有边界了。

**Comment by haozibi** [comment]
> 不能用kcp的分包，你Write(1GB []byte)就超过255分片了

是为了性能和避免错误，所以不使用 kcp 的分片？
ps： 用 udp 传输文件，特别是大文件，是不是一个错误的方向？

**Comment by xtaci** [comment]
你直接用kcptun传大文件就行了

**Comment by haozibi** [comment]
> 你直接用kcptun传大文件就行了

嗯嗯，好的，我看一下 kcptun 的代码，谢谢
