### ISSUE TITLE
数据有可能错掉

### ISSUE THREAD

**Issue by zx9597446** [xtaci/kcp-go#12]
类似kcptun，在kcp-go上再套上yamux，两台服务器之间传输数据，服务端用一个简单的echoserver，写了一个测试程序，每隔50ms发送1024个字节的数据，然后计算RTT延迟，延迟是比较小（0-15ms），但是运行到一定的数量，yamux会输出invalid protocol version错误，然后连接断掉，使用还没加SetACKNodelay的版本，就不会这样但是延迟会稍微高些（50ms左右，具体哪个版本现在无法找回了），测试程序是这个：
https://github.com/zx9597446/echoping
现在不能确定是kcp-go的问题，还是yamux的问题，怀疑是kcp-go发送的数据会有一定几率错掉？

**Comment by xtaci** [comment]
如果不是官方的release版本，建议换成官方release再测试，非官方版本是快照，一定有少量问题

**Comment by zx9597446** [comment]
官方release指的是kcp-go还是kcptun？

**Comment by xtaci** [comment]
kcptun一定要用release， kcp-go更新到最新就行了

**Comment by zx9597446** [comment]
我这边是没有直接用kcptun的，是自己在kcp-go上套的yamux，但代码是跟kcptun类似的。

**Comment by xtaci** [comment]
这个问题
1. 我是长期运行的服务器客户端，这个问题曾经（大概两三周前）确实出现过，但后来再也没有出现过。
2. 建议检查一下客户端和服务器的编译环境，是不是用了不同的yamux版本，go的版本管理很蛋痛。

**Comment by zx9597446** [comment]
yamux的commits我看了下，最近基本没有大的改动，我是用kcp-go大概3周之前的，比较稳定，但延迟会在50ms左右，用最新的kcp-go, 延迟基本在0，偶尔到15或者更高。我再观察下吧，谢谢及时的回复！

**Comment by xtaci** [comment]
嗯，我再review一下code

**Comment by zx9597446** [comment]
还有就是两种环境测试，一种是我家里到美国的vps，延迟很高，100ms以上，用fast2模式，没有加密，发送17万个数据包没有出现invalid protocol version，从佛山到香港，两台服务器，速度很快，0-15ms，一般几万个数据包就会出现。

**Comment by xtaci** [comment]
这个问题很重要，需要快速分析解决

**Comment by zx9597446** [comment]
我观察到情况是在压力比较大，发送频率很快（50ms发一次，1024个字节）延迟很低（0-15ms）的情况下，比较容易发生，一般就是几万个就断掉。

**Comment by zx9597446** [comment]
基本上normal/fast/fast2/fast3还有acknodelay, sndwnd/recvwnd各种参数都尝试过。

**Comment by xtaci** [comment]
如果你是自己编译的话，我有个地方一直比较怀疑，你可以试一下

```
392             n, err := s.conn.WriteTo(ping, s.remote)
393             if err != nil {
394                 log.Println(err, n)
395             }
```

把sess.go 的这几行注释掉编译，不发送ping

**Comment by zx9597446** [comment]
好的，我测试下。

**Comment by xtaci** [comment]
另外，你测试的时候，带有fec么？

**Comment by zx9597446** [comment]
fec=4 fec=1 fec=0都测试过，都会出现。

**Comment by xtaci** [comment]
我这里始终无法重现， 用的kcptun release

**Comment by zx9597446** [comment]
我怀疑跟发送频率有关，貌似去掉那段代码后就稳定了，目前跑了5万个包了，尚未出现。

**Comment by xtaci** [comment]
嗯，这个问题可能和系统random发生器有关，但确实是个问题。
我等下把这个问题fix一下

**Comment by xtaci** [comment]
我简单fix了下这个问题，测试一下最新的commit

**Comment by zx9597446** [comment]
392             n, err := s.conn.WriteTo(ping, s.remote)
393             if err != nil {
394                 log.Println(err, n)
395             }
去掉这段代码，大约收发了10万个包后连接断开了，又运行了一次，用5个连接，很快1条连接就发生了invalid protocol version，我现在用你的commit测试下。

**Comment by xtaci** [comment]
@zx9597446

你在你的测试程序，就是引用kcp-go的那个程序，加了Seed设定么？
```
 57 func main() {
 58     rand.Seed(int64(time.Now().Nanosecond()))
```

**Comment by zx9597446** [comment]
没有加Seed

**Comment by xtaci** [comment]
没有加Seed一定有问题的，你再更新一下kcp-go，我在library加上了，
如果你不加，结果就是每次都是用的同一个端口，同一个会话ID上一次的数据包就和这一次的重复了

**Comment by zx9597446** [comment]
好的，我测试下

**Comment by zx9597446** [comment]
kcp-go还需要额外的端口吗？除了我自己指定listen或者connect的端口？

**Comment by xtaci** [comment]
不需要,但是UDP是无状态的， 路由器NAT会认为是同一个回话，必须通过切换端口和conv id的方式来让让NAT更新端口映射，从而让服务器知道，哦，这个是一个新的回话。

之前没加rand，每次本地的端口必定一样，是无法区分会话的。

**Comment by zx9597446** [comment]
昨天有点事情，可能更新又出了点问题，还没来得及好好测试，这几天我会再测试下，看是不是Seed的问题，感谢@xtaci的及时回复。

**Comment by zx9597446** [comment]
@xtaci 用了最新的版本，fec=4, mode=fast2，acknodelay=0，sndwnd/rcvwnd=1024 我的main中加了Seed和没加Seed都测试了，还是会出现invalid protocol version: [随机数字]

**Comment by xtaci** [comment]
实在难以分析，我建议你用kcptun做echoping的实验

**Comment by zx9597446** [comment]
好的，我用kcptun测试下。

**Comment by zx9597446** [comment]
终于找到错误了，是我的代码里面，ListenWithOptions的实际上传递了mtu参数进去，而不是fec参数。谢谢@xtaci

**Comment by xtaci** [comment]
不过歪打正着review出了一个bug，挺好
