### ISSUE TITLE
kcp.stream 选项无效

### ISSUE THREAD

**Issue by ZezhongWang** [xtaci/kcp-go#121]
自己尝试了一下，发现 kcp.stream 这个参数实际上是无效的，无论是否开启，发送的时候都会拆成 mss 的大小，接收端在 kcp.stream = 0 的时候也无法完成 merge。

主要原因是在 session.Write 的时候就已经拆成了 mss 的大小进行 send：
```

                // controls how much data will be sent to kcp core
		// to prevent the memory from exhuasting
		if s.kcp.WaitSnd() < int(s.kcp.snd_wnd) {
			n = len(b)
			for {
				if len(b) <= int(s.kcp.mss) {
					s.kcp.Send(b)
					break
				} else {
					s.kcp.Send(b[:s.kcp.mss])       //拆成 mss 大小
					b = b[s.kcp.mss:]
				}
			}
                       ......
               }
```

这样在 kcp.Send 的时候，就无法进行 frg 编号，因为这一层接收到的都已经是小于 mss 大小的了。

```
         if kcp.stream != 0 {
		// 1. 流模式：取出 snd_queue 中的最后一个报文
		// 将其填充到 mss 的长度
		n := len(kcp.snd_queue)
		if n > 0 {
			seg := &kcp.snd_queue[n-1]
			if len(seg.data) < int(kcp.mss) {
				capacity := int(kcp.mss) - len(seg.data)
				extend := capacity
				if len(buffer) < capacity {
					extend = len(buffer)
				}

				// grow slice, the underlying cap is guaranteed to
				// be larger than kcp.mss
				oldlen := len(seg.data)
				seg.data = seg.data[:oldlen+extend]
				copy(seg.data[oldlen:], buffer)
				buffer = buffer[extend:]
			}
		}

		if len(buffer) == 0 {
			// 无剩下数据，直接返回
			return 0
		}
	}
```

不过正如Write的注释所说，如果直接Send接收完整数据，程序会崩掉，为了防止内存耗尽才这么做。所以这是作者的遗留bug？？

另外也想请教一下，按道理 slice 作为参数是传指针，是因为什么会造成在 Write 层面不拆就会导致内存耗尽呢？

**Comment by xtaci** [comment]
frg最多只能255，超过了就不行，必须分片，kcp-go不兼容消息模式，net.Conn读写语义也不兼容

**Comment by ZezhongWang** [comment]
不是，你仔细看看代码，现在 frg 字段是不生效的，无论如何都是0。

因为在 Write 的时候已经拆成了 mss 大小，而 Send 中的分片只对于比 mss 大的生效。所以说 frg 不生效。

    func (kcp *KCP) Send(buffer []byte) int { // 这里 len(buffer) < mss 恒成立
        ...
 	// 2. 计算剩下的数据需要被划分成几段
	if len(buffer) <= int(kcp.mss) {             
		count = 1
	} else {
		count = (len(buffer) + int(kcp.mss) - 1) / int(kcp.mss)        // 无法抵达
	}
	// 3. 为剩下数据创建 kcp segment，添加到 snd_queue 尾部
	for i := 0; i < count; i++ {          // 所以这里的count == 1 也恒成立
		var size int
		if len(buffer) > int(kcp.mss) {
			size = int(kcp.mss)
		} else {
			size = len(buffer)
		}
		seg := kcp.newSegment(size)
		copy(seg.data, buffer[:size])
		if kcp.stream == 0 { // message mode
			seg.frg = uint8(count - i - 1)
		} else { // stream mode
			seg.frg = 0
		}
		kcp.snd_queue = append(kcp.snd_queue, seg)
		buffer = buffer[size:]
	}

**Comment by xtaci** [comment]
对啊，所以干脆就放弃frg了，不支持消息模式。

**Comment by ZezhongWang** [comment]
这样哦。。那还不如把 frg 字段删了。。挺有歧义的，还占包头字节

**Comment by xtaci** [comment]
不删，保持协议兼容性

**Comment by isjarvi** [comment]
是否可以提供一个支持消息模式的分支，在我使用的场景中，消息包基本不会超过（1376*255）这个大小
