### ISSUE TITLE
kcp 连接一个不存在的地址，不报错误

### ISSUE THREAD

**Issue by YaIce** [xtaci/kcp-go#124]
kcpconn, err := kcp.DialWithOptions("10.0.0.11:10001", nil, 10, 3)

	if err != nil {
		fmt.Println("kcp err",err.Error())
		return
	}
	_kcpconn = kcpconn

	i,err := _kcpconn.Write([]byte("hello kcp.emmmmmmmmmmmmmmm"))
地址不存在的情况下，依然还是能够发包，不报错误。

**Comment by xtaci** [comment]
udp无连接
