### ISSUE TITLE
有个Session Write问题

### ISSUE THREAD

**Issue by bianchengxiaobei** [xtaci/kcp-go#127]
UDPSession Write方法，
if len(b) <= int(s.kcp.mss) {
					s.kcp.Send(b)
					break
				} else {
					s.kcp.Send(b[:s.kcp.mss])
					b = b[s.kcp.mss:]
				}
这个方法，当b的大小超过mss的大小时，都是采用流模式不能用消息模式，你在kcp.Send里面已经判断kcp.mss的比较，所以这里应该不用for循环，直接s.kcp.Send(b)

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/issues/89
https://github.com/xtaci/kcp-go/issues/116
https://github.com/xtaci/kcp-go/issues/121
