### ISSUE TITLE
在哪里下载6-29日前的版本？

### ISSUE THREAD

**Issue by maoxxyy** [xtaci/kcp-go#13]
现在用kcp-csharp的客户端连接kcp-go的服务端有问题，
注意到kcp-go是在6-29提交的新文件，而kcp-csharp的最后更新是在5月份。
不知在哪里能下载5月之前的kcp-go版本，谢谢

**Comment by xtaci** [comment]
用默认的Dial就可以，关闭加密，关闭FEC

**Comment by maoxxyy** [comment]
好的，多谢，我试下
响应好快啊！

**Comment by maoxxyy** [comment]
屏蔽掉加密和fec后可以连接了，谢谢
