### ISSUE TITLE
请教一下kcp-go的性能问题

### ISSUE THREAD

**Issue by spiderpoison** [xtaci/kcp-go#130]
测试场景：
&emsp;游戏战斗帧同步，20人一个房间，每人50ms发一个消息，每个房间每50ms将此帧所有人消息广播给所有人。
实现方式：
&emsp;每人kcp连接到服务器，收/发是独立的goroutine，每个房间单独的goroutine。
测试机：
&emsp;阿里云，8核2.5GHz。CentOS Linux release 7.4.1708 (Core)。2台，一台跑服务器程序，一台跑客户端程序。

测试结果：
&emsp;2000人，服务器那台机器cpu占用340%左右，客户端那台机器cpu占用380%左右。响应时间毫秒级
&emsp;2500人，响应时间明显恶化，达到800毫秒
&emsp;超过2500人，开始有掉线情况

pprof看cpu占用，绝大部分是在kcp的read和write上。
请问我的这种使用方式是否有问题？kcp-go的性能是否就是这样？

（ps: 我自己的定时器开始用的go自身的ticker，后来改为了sleep模拟定时）

**Comment by xtaci** [comment]
最好的方式是pprof，开火焰图看瓶颈在哪里，UDP的sendto 系统调用和tcp的write调用不是一个level的开销

**Comment by spiderpoison** [comment]
2000人，火焰图, kcp-go占用大概如下：
kcp-go.Read 14%
kcp-go.Write 24%
kcp-go.monitor 10%
kcp-go.updateTask 7%

cpu约350%，load在4左右，但是继续加人，就会恶化甚至掉线。
请问是否到了性能极限，我还有什么优化空间吗？

**Comment by medusar** [comment]
顺便问一句，你们测试的客户端延迟有跟TCP对比嘛？效果如何？

**Comment by spiderpoison** [comment]
还想请教一下kcp的网络流量占用问题。

我写了简单的kcp测试客户端和服务器：
&emsp; 客户端：每50ms发送10byte，然后等待接受
&emsp; 服务端：等待接受，然后每50ms发送150byte
用6000人测试，理论上服务器流量每秒10Mbps
但从阿里云的网络监控上看，流量是理论值的2~20倍
我的kcp参数如下：
StreamMode：false
NoDelay：1, 10, 2, 1
Mtu：1024
ACKNoDelay： false
ReadBuffer：1024 * 16
WriteBuffer：1024 * 16

请问这个带宽占用情况是正常的吗？

**Comment by yaohong** [comment]
> 还想请教一下kcp的网络流量占用问题。
> 
> 我写了简单的kcp测试客户端和服务器：
>   客户端：每50ms发送10byte，然后等待接受
>   服务端：等待接受，然后每50ms发送150byte
> 用6000人测试，理论上服务器流量每秒10Mbps
> 但从阿里云的网络监控上看，流量是理论值的2~20倍
> 我的kcp参数如下：
> StreamMode：false
> NoDelay：1, 10, 2, 1
> Mtu：1024
> ACKNoDelay： false
> ReadBuffer：1024 * 16
> WriteBuffer：1024 * 16
> 
> 请问这个带宽占用情况是正常的吗？
你好。你线上项目有用这个库嘛

**Comment by yaohong** [comment]
@spiderpoison
你好请问你线上环境有使用这个库嘛

**Comment by xtaci** [comment]
带宽占用不正常

**Comment by spiderpoison** [comment]
@yaohong 准备在线上使用呢

**Comment by spiderpoison** [comment]
@xtaci 请问和我的参数有关吗，还是阿里云的监控有问题，我应该如何进一步确认流量问题？

**Comment by xtaci** [comment]
可能是你估算方法有偏差，实际流量2倍左右是合理得。

**Comment by yaohong** [comment]
可以交流下。我现在也准备使用这个。 ------------------ 原始邮件 ------------------
发件人: "spiderpoison"<notifications@github.com>
发送时间: 2019年7月8日(星期一) 晚上8:14
收件人: "xtaci/kcp-go"<kcp-go@noreply.github.com>;
抄送: "yaohong"<231344781@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [xtaci/kcp-go] 请教一下kcp-go的性能问题 (#130)



@yaohong 准备在线上使用呢
 
&mdash;

**Comment by wjl419170079** [comment]
遇到同样的问题，请问这个问题后来怎么解决的呀
