### ISSUE TITLE
可能存在重复执行的情况

### ISSUE THREAD

**Issue by yanchuang12** [xtaci/kcp-go#133]
https://github.com/xtaci/kcp-go/blob/4b6ad7e691060bd3656a4bf0ffb0659505c7aeb1/kcp.go#L413

对端，只要在合理的窗口范围内，会针对每个数据包返回一个ack。 这样存在重复针对一个数据的ack， 这段代码就会针对同一个seg delSegment多次， 要在前面判断增加是否已经acked更好些吧

**Comment by xtaci** [comment]
delSegment会判断

**Comment by yanchuang12** [comment]
判断放到里面了
