### ISSUE TITLE
windows编译错误

### ISSUE THREAD

**Issue by nh-live** [xtaci/kcp-go#134]
2019/07/18 16:18:56 ERROR    ▶ 0015 Failed to build the application: # github.com/xtaci/kcp-go
..\..\github.com\xtaci\kcp-go\sess.go:475:39: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt
..\..\github.com\xtaci\kcp-go\sess.go:481:39: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt
..\..\github.com\xtaci\kcp-go\sess.go:481:67: undefined: syscall.IPV6_TCLASS
..\..\github.com\xtaci\kcp-go\sess.go:841:39: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt
..\..\github.com\xtaci\kcp-go\sess.go:847:39: cannot use int(fd) (type int) as type syscall.Handle in argument to syscall.SetsockoptInt
..\..\github.com\xtaci\kcp-go\sess.go:847:67: undefined: syscall.IPV6_TCLASS

**Comment by xtaci** [comment]
fixed

**Comment by nh-live** [comment]
tks
