### ISSUE TITLE
请教一个ack的问题

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#135]
https://github.com/xtaci/kcp-go/blob/b8cc8a83fb1cb0645a133c09a5f7c2407bfb48dd/kcp.go#L693

len(kcp.acklist)-1 == i

请教个问题，什么情况下必须把最后一个包必须发出去？如果所有的ack包都小于rcv_nxt应该就不需要这个条件呢？

**Comment by alex-jin** [comment]
我也很想知道

**Comment by xtaci** [comment]
很简单，你只要需要一个包来告知对方una

**Comment by xtaci** [comment]
从接收方的角度， 有两种方式告诉对方本方收到了哪些包：

1. seg.una，小于这个值的，全部都已收到
2. seg.ack，本包收到。

引理: 在一个internal周期内收到的所有包，累计若干ack到acklist:
如果在周期结束后，acklist中， seg.ack < seg.una（kcp.rcv_nxt)， 那无需告诉对方每个具体的ack 1 2 3包的确认，因为已经范围确认了。只有未被范围确认的，才需要独立发送ack。

**Comment by l42111996** [comment]
懂了，谢谢
