### ISSUE TITLE
关于带宽利用问题 

### ISSUE THREAD

**Issue by sgf** [xtaci/kcp-go#14]
是否可以参考 
https://github.com/v2ray/manual/blob/master/zh_cn/chapter_03/kcp.md
https://www.v2ray.com/zh_cn/chapter_02/01_overview.html
思路进一步优化 KCP的能力呢？
就好像 传说中的FastTcp 一样。。。。
鱼和熊掌 尽量兼得。

**Comment by xtaci** [comment]
鱼和熊掌是啥

**Comment by sgf** [comment]
老大 我说的 鱼和熊掌是 延迟和带宽利用率  o(╯□╰)o

**Comment by xtaci** [comment]
这个不可能的哈，香农定理决定了。

**Comment by xtaci** [comment]
你把丢包看成：信噪比， 传输窗口看为 ：带宽

香农定理由如下的公式给出: C=W*log2*(1+S/N) 其中C是可得到的链路速度，W是链路的带宽，S是平均信号功率,N是平均噪声功率，信噪比（S/N）通常用分贝（dB）表示，分贝数=10×log10（S/N）。

**Comment by sgf** [comment]
谢谢 我也在 kcp 项目提了 作者也是觉得 过于扣带宽占用的话 也不是太好 或许会带来反作用。
@xtaci  同时 也感谢你的 耐心 解答 
我没有问题了 以后继续低调学习ing
