### ISSUE TITLE
这里是否应该判断一下时间？

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#143]
https://github.com/xtaci/kcp-go/blob/d59f410c97d58cd207c92063157991d723cf24a3/kcp.go#L578

因为包的乱序，这里感觉应该使用最大的一个值做rtt

**Comment by xtaci** [comment]
不是最大，是最后一个

**Comment by l42111996** [comment]
由于乱序 ，最后一个包可能是前面的某个包的时间 ，反应的是那个时间点的rtt，最近的包更能反馈最近时间点的rtt

**Comment by xtaci** [comment]
时间上最后到达的，就是最接近网络上真实情况的

**Comment by xtaci** [comment]
现代网络上，乱序的可能性极低，几乎没有
