### ISSUE TITLE
Allow using custom transport, or allow writing/reading out of bound packets.

### ISSUE THREAD

**Issue by AudriusButkevicius** [xtaci/kcp-go#15]
Usecase:
STUN/DHT on the same UDP connection.

If I could write and read out of bound (non KCP session) packets, I could easily do that.
Also, if I could provide my own transport, I could perform packet framing to identify DHT/STUN packets from KCP packets, and route them accordingly.

**Comment by xtaci** [comment]
maybe you can modify ReadFromUDP from here:
https://github.com/xtaci/kcp-go/blob/master/sess.go#L527

for kcp-go, compatibility with all c/c#/go versions is a must.

**Comment by AudriusButkevicius** [comment]
I'll make a pull request once I've achieved what I want.

**Comment by AudriusButkevicius** [comment]
How much do you care about API changes?

**Comment by xtaci** [comment]
As compatible as possible, some function like```SetSTUN(enable bool)``` is prefered if you wish to PR.n

**Comment by AudriusButkevicius** [comment]
So STUN will obviously will have to be performed externally because you can't just send KCP packets to the STUN servers and you might have to send them periodically which means you need to be able to distinguish the different streams. The API change I am talking about is passing a connection variable to (Listen/Dial)WithOptions, or should I make a new method to preserve the API?

**Comment by xtaci** [comment]
@AudriusButkevicius I think changes to  (Listen/Dial)WithOptions is acceptable. 
But, I do not know much about STUN, maybe you can just show me the code, and then we can find a better solution for API changes.

**Comment by xtaci** [comment]
@AudriusButkevicius  I'm reading documents about STUN. we can discuss about APIs later.
