### ISSUE TITLE
How to reduce kcp overhead?

### ISSUE THREAD

**Issue by WinstonPrivacy** [xtaci/kcp-go#151]
We've noticed KCP introduces a large overhead on top of ordinary network communications in terms of the total bytes transferred.

For instance, a live test node currently shows:

- Application sent: 689kB
- KCP sent: 4,854kB

- Application received: 7,093kB
- KCP received: 12,234kB

Is there a way to tune the settings to reduce the amount of overhead? Our application is using SMux as well, so possibly the problem may lie there as well.

**Comment by WinstonPrivacy** [comment]
Looks like most of the overhead is coming from FEC. Disabling it helps a lot.

**Comment by xtaci** [comment]
every benefits comes with costs
