### ISSUE TITLE
tls supports?

### ISSUE THREAD

**Issue by acrazing** [xtaci/kcp-go#156]
I found this project implements symmetrical encryption with custom headers. Is it possible to use with `tls`? We want to use `kcp` in public client side, that means the static secret is not secure.

**Comment by xtaci** [comment]
https://golang.org/pkg/crypto/tls/
TLS works on net.Conn and net.Listener, which kcp-go supports

**Comment by acrazing** [comment]
I see, thanks.

**Comment by dedo1911** [comment]
Is there any example available? Thanks!
