### ISSUE TITLE
关于ack的一点想法

### ISSUE THREAD

**Issue by alex-jin** [xtaci/kcp-go#159]
现在的逻辑是ack.sn >= kcp.rcv_nxt 才给对方回一个ack，不应该是ack.sn>=seg.una 么？ kcp.rcv_nxt是会并发变的。难道你的本意是kcp.rcv_nxt变化的话就在下次flush的时候再用seg.una一起ack了？谢谢

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/issues/135

**Comment by alex-jin** [comment]
那个问题的答案我看懂了， 但是我的问题和他不一样， 我的问题是代码从seg.una = kcp.rcv_nxt到ack.sn >= kcp.rcv_nxt之间如果kcp.rcv_nxt变大的话  seg.una~kcp.rcv_nxt之间的包在这次flush就不会发送对应的ack了吧？

**Comment by xtaci** [comment]
是的，update interval 那一刻（10ms -40ms） 结算， 就是因为会变大，这个判断才有用。
