### ISSUE TITLE
timedsched.go的sched()函数问题

### ISSUE THREAD

**Issue by alex-jin** [xtaci/kcp-go#161]
比如sched()对应的timedFuncHeap里有2个任务的时候，timer的触发时间有可能不是堆顶的任务需要执行的时间，而是第二个任务需要执行的时间。因为从ts.chTask里出来的任务的执行时间是无序的，有可能后出来的需要先执行。

**Comment by xtaci** [comment]
没有关系，不需要严格时序，只需要after deadline后触发，并as soon as possible就行

**Comment by alex-jin** [comment]
好吧，感谢回复
