### ISSUE TITLE
请教个BlockCrypt问题

### ISSUE THREAD

**Issue by olewaLdeisi** [xtaci/kcp-go#176]
大佬好，我是个go新手，想用到kcp来建立连接有点疑惑：加密的密钥只能写死吗？有没有办法先建立连接，服务端和客户端协商密钥，后面再加密传输数据？

**Comment by xtaci** [comment]
办法太多了，DH, ECDH....

**Comment by olewaLdeisi** [comment]
emmm，我的意思是： 我看了下代码，ListenWithOptions方法传入了一个block，每当有新的客户端连接过来时，服务端listener都会在packetInput方法中用这个block解密，然后new一个有这个block的UDPSession，而block是私有字段，好像没有提供办法在创建listener示例之后修改这个字段

**Comment by xtaci** [comment]
那你就先协商出Block，然后New的时候有个方法传入已经建立好的net.Conn和block
