### ISSUE TITLE
有几个问题。

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#180]
https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L1053
在segment被标记为acked之后这里的snd_buf应该把acked的数量排除

https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L661
这里可以是 else if  。。减少一次flush

**Comment by l42111996** [comment]
https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L407
https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L429
这两个函数可以合并

**Comment by xtaci** [comment]
> https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L1053
> 
> 
> 在segment被标记为acked之后这里的snd_buf应该把acked的数量排除

不能排除，窗口的滑动是尺寸固定，要不有可能一直在发送后面的数据，第一个永远没有机会被ack，带宽竞争下的第一个包丢掉。

> https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L661
> 
> 
> 这里可以是 else if 。。减少一次flush

这里可以，不影响功能，可以fix

**Comment by xtaci** [comment]
> https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L407
> 
> 
> https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L429
> 
> 
> 这两个函数可以合并

无所谓了，不同的逻辑

**Comment by l42111996** [comment]
> > https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L1053
> > 
> > 在segment被标记为acked之后这里的snd_buf应该把acked的数量排除
> 
> 不能排除，窗口的滑动是尺寸固定，要不有可能一直在发送后面的数据，第一个永远没有机会被ack，带宽竞争下的第一个包丢掉。

我看原版这里是被排除的，ack标记是为了逻辑删除到收到对应una之后进行实际删除。发送队列的长度应该是排除那些ack的长度。

**Comment by xtaci** [comment]
> > > https://github.com/xtaci/kcp-go/blob/43d2c47d8ac1faf652f7f8dbc012c39339b2db13/kcp.go#L1053
> > > 
> > > 在segment被标记为acked之后这里的snd_buf应该把acked的数量排除
> > 
> > 
> > 不能排除，窗口的滑动是尺寸固定，要不有可能一直在发送后面的数据，第一个永远没有机会被ack，带宽竞争下的第一个包丢掉。
> 
> 我看原版这里是被排除的，ack标记是为了逻辑删除到收到对应una之后进行实际删除。发送队列的长度应该是排除那些ack的长度。

不影响的，实际窗口是snd_una滑动的，而不是这里的值，我改成这样应该是更准确的，要不即使发送到kcp内部，也不会传送。

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L765

窗口是snd_una + cwnd这么大，也就是最前端的包的seqid和seqid+cwnd这个包的id的一个固定值
