### ISSUE TITLE
Send data to special address  

### ISSUE THREAD

**Issue by farzadi** [xtaci/kcp-go#191]
How can I send data to a special IP address?
If I use UDPConn itself like the code below I can send data to a special IP address

```
func send(m []byte, conn *net.UDPConn, addr *net.UDPAddr) {
	_, err := conn.WriteToUDP(m, addr)
	if err != nil {
		fmt.Printf("Couldn't send response %v", err)
	}
}
```
how can I do something like this with KCP?

**Comment by xtaci** [comment]
no , kcp is session oriented. you don't need kcp if you just send arbitary packets to random ip addresses

**Comment by farzadi** [comment]
Thank you for your answer. 
So in that case if for example we have two separate rooms which have some user in each of them that they want to talk to each other in their own rooms not possible ? I want to reach something like this.

**Comment by xtaci** [comment]
the communcation cost for this case is O(N^2), i.e. one connection for each pair.

**Comment by farzadi** [comment]
Thank you so much.
