### ISSUE TITLE
How to catch "connection refused" error

### ISSUE THREAD

**Issue by panjiang** [xtaci/kcp-go#192]
I need to detect the error when connecting to unreachable destination port. 

### UDP can
```go
conn, err := net.Dial("udp", "localhost:12345")
for {
	n, err := conn.Write([]byte("Hello"))
	log.Println(n, err)
	time.Sleep(time.Second)
}

// Output:
// 2021/01/27 15:12:09 5 <nil>
// 2021/01/27 15:12:10 0 write udp 172.21.144.35:33671->10.7.0.68:12345: write: connection refused
```

Syscall `SYS_WRITE`
```go
// go/src/syscall/zsyscall_linux_amd64.go:914
r0, _, e1 := Syscall(SYS_WRITE, uintptr(fd), uintptr(_p0), uintptr(len(p)))
// e1: ECONNREFUSED (111)
```

### KCP can't
```go
conn, err := kcp.Dial("localhost:12345")
for {
	n, err := conn.Write([]byte("Hello"))
	log.Println(n, err)
	time.Sleep(time.Second)
}

// Output:
// 2021/01/27 15:15:54 5 <nil>
// 2021/01/27 15:15:55 5 <nil>
```

Syscall `sysSENDMMSG`
```go
// golang.org/x/net/internal/socket/sys_linux.go:20
 n, _, errno := syscall.Syscall6(sysSENDMMSG, s, uintptr(unsafe.Pointer(&hs[0])), uintptr(len(hs)), uintptr(flags), 0, 0)
// errno: 0
```

**Comment by xtaci** [comment]
oh, this can only happen on localhost, right?

**Comment by panjiang** [comment]
Tanks for quick reply.

It works on any host which have not disable related type ICMP. Like this:

```
iptables -I OUTPUT -p icmp --icmp-type destination-unreachable -j DROP
```

The same result was occurred after replacing destination with `crownote.com:12345` (my remote host).

**Comment by xtaci** [comment]
oh, it's not easy, because ICMP message is triggered from kernel.

**Comment by xtaci** [comment]
It's a problem related to 
https://github.com/xtaci/kcp-go/blob/master/sess.go#L1046
here I use **Listen** instead of **Dial**, the difference is **Dial** is a **connected UDP socket**, which may receive ICMP message, while the other can't.

**Comment by panjiang** [comment]
Yes it is, so I have to give up this way. 
I will try to cooperate with another TCP connection, close KCP when the TCP disconnected.
