### ISSUE TITLE
ping包完全随机？

### ISSUE THREAD

**Issue by FTwOoO** [xtaci/kcp-go#21]
如下代码是发送ping包的outputTask()的片段，客户端和服务端都会发送，发送的是完全随机的字节:

```
		case <-ticker.C: // NAT keep-alive
			if len(s.chUDPOutput) == 0 {
				s.mu.Lock()
				interval := s.keepAliveInterval
				s.mu.Unlock()
				if interval > 0 && time.Now().After(lastPing.Add(interval)) {
					sz := s.rng.Intn(IKCP_MTU_DEF - s.headerSize - IKCP_OVERHEAD)
					sz += s.headerSize + IKCP_OVERHEAD
					ping := make([]byte, sz)
					io.ReadFull(crand.Reader, ping)
					n, err := s.writeTo(ping, s.remote)
					if err != nil {
						log.Println(err, n)
					}
					lastPing = time.Now()
				}
			}

```

那么有疑问，就是ping包发送的是完全随机的字节：
假如开启了加密，好么接收端收到这些完全随机的ping包，会校验失败而忽略掉，但是ping包导致的校验错误会记录到DefaultSnmp.InCsumErrors中，这不是所期望的吧？:

```
	for {
		select {
		case p := <-chPacket:
			raw := p.data
			data := p.data
			from := p.from
			dataValid := false
			if l.block != nil {
				l.block.Decrypt(data, data)
				data = data[nonceSize:]
				checksum := crc32.ChecksumIEEE(data[crcSize:])
				if checksum == binary.LittleEndian.Uint32(data) {
					data = data[crcSize:]
					dataValid = true
				} else {
					atomic.AddUint64(&DefaultSnmp.InCsumErrors, 1)
				}
			} else if l.block == nil {
				dataValid = true
			}
			s.kcpInput(data)
```

即便是开启了加密和CRC，也有极小的概率出现随机产生的数据包恰巧验证通过而被当成了正常的数据包，这样情况也是异常的。不知我的理解正不正确？

**Comment by xtaci** [comment]
这就是预期的行为，故意如此设计， 直到宇宙灭亡的时候才可能产生一个能通过传输层的包，然而也无法通过TLS层。但对于反破译有很大的扰乱作用。

**Comment by FTwOoO** [comment]
嗯，主要是前面那个，如果这是服务端，又有很多人同时使用，那么InCsumErrors这个值把ping包也算进去，不就废了- -

**Comment by xtaci** [comment]
没关系的， 就是这么设计的。完全不影响。

**Comment by FTwOoO** [comment]
还有就是， 如果没开启加密， 是不是ping包就过滤不掉了？

**Comment by xtaci** [comment]
会在协议层过滤， 通过概率变高， 大概是 1/ 2^68 的概率

**Comment by FTwOoO** [comment]
哈算得真清楚

**Comment by FTwOoO** [comment]
你是说在KCP那边的过滤？

**Comment by xtaci** [comment]
是的，重算了下：  convid 32bit + sn 32bit + length 32bit + cmd 8bit + frg 8bit 都要是正确的取值才行，  是 1/ 2^112的概率。

**Comment by AudriusButkevicius** [comment]
Why can't you just send a valid kcp data packet with a 0 data length?

**Comment by xtaci** [comment]
why should this packet enter KCP core? just drop it from outside. @AudriusButkevicius

**Comment by AudriusButkevicius** [comment]
Sure, but then you have skewed stats, and if someone does some packet filtering based on the packet signature (like I do, to separate stun and kcp packets), you get screwed up by these random packets being sent.

I ended up disabling keepalives at KCP and just hope that yamux pings and stun discoveries will keep the NAT mapping alive.

**Comment by xtaci** [comment]
@AudriusButkevicius I think yamux pings are completely un-usable, I'm seeking a better way to detect pings, not on the yamux level.  It could not sense the transferring speed,  so a normal large-flow stream would BLOCK the ping packet .

**Comment by xtaci** [comment]
@AudriusButkevicius https://github.com/hashicorp/yamux/pull/38

试图修正yamux 的io deadline 问题

**Comment by xtaci** [comment]
@AudriusButkevicius  how about this one: 
https://github.com/xtaci/yamux/commit/a4898a825ef5265c55595548c3a32d9abedf683a

**Comment by FTwOoO** [comment]
我还是觉得这个ping可以做成可选开关，不排除有人想在应用层做ping（结合其它功能）
