### ISSUE TITLE
csharp客户端能建立连接，但是没法收到消息

### ISSUE THREAD

**Issue by okitaAsuka** [xtaci/kcp-go#218]
客户端的kcp库：https://github.com/vis2k/kcp2k

服务端这边断点是能断到连接进来(accept到udpSession)，但是之后客户端发的消息都读不到(udpSession.Read)，想问一下可能是哪里有问题呢?

**Comment by cloud136731** [comment]
请问最后找到问题了吗？我也遇到类似的问题，能不能交流下
