### ISSUE TITLE
why IKCP_OVERHEAD is 24bytes

### ISSUE THREAD

**Issue by jnxyatmjx** [xtaci/kcp-go#236]
why IKCP_OVERHEAD is 24bytes and how to calculate  it？

**Comment by RobertCXJ** [comment]
conv = 4 bytes    cmd = 1 byte    frg = 1 byte    wnd = 2bytes
ts = 4 bytes    sn = 4 bytes
una = 4 bytes    len = 4 bytes
a segment contains these fields,  a total of 24 bytes

**Comment by jnxyatmjx** [comment]
> conv = 4 bytes cmd = 1 byte frg = 1 byte wnd = 2bytes ts = 4 bytes sn = 4 bytes una = 4 bytes len = 4 bytes a segment contains these fields, a total of 24 bytes

thank you very much.
