### ISSUE TITLE
how to handle timeout

### ISSUE THREAD

**Issue by Dethrail** [xtaci/kcp-go#25]
Hi, can you assist me with little issue?
For example, I create connection and setup KeepAlive to 5 seconds:
KCPConn.SetKeepAlive(5)

After this I am put down client and wait some time. The next code gives following results:
```
	log.Print("send1\n")
	l, err := c.KCPConn.Write(p.Serialize())
	log.Print("send2\n")
```

> 2016/12/30 14:21:46 send1
> 2016/12/30 14:21:46 send2
> ...
> 2016/12/30 14:21:57 send1

Connection has lived more than 5 sec and I don't know how to process this error. 

Apologize for my bad English.
Regards,
Max.

**Comment by xtaci** [comment]
you should use SetReadDeadline/SetWriteDeadline


https://golang.org/pkg/net/#Conn
