### ISSUE TITLE
Use of deprecated crypto libraries

### ISSUE THREAD

**Issue by faddat** [xtaci/kcp-go#256]
kcp-go currently uses a number of deprecated crypto libraries, including some that have been broken.

This issue is solved in #254 but that may make sense to break into its own PR.  I also wanted to know if there's an intentional reason that they were being used.

**Comment by xtaci** [comment]
they're not broken, these crypto algos were included on purpose.

**Comment by faddat** [comment]
Thank you very much 🙂

I'll pull those changes out of my PR in that case. Some of them do report as broken but I think I understand what you mean about their being included on purpose.

They do however show big big huge deprecation warnings and... what are your thoughts on that?

I'm thinking about this from the perspective of a downstream integrator and basically what's going to happen is when KCP-go is imported, downstream users are likely to get all kinds of warnings in their own ci systems about the libraries kcp uses. 

Thanks so much for your work here over several years.

I have built a number of prototypes using kcp-go and really enjoy it.
