### ISSUE TITLE
Need a assistance with Read... (memory leak)

### ISSUE THREAD

**Issue by Dethrail** [xtaci/kcp-go#27]
for now I'm using like that:

```
var (
	buf = make([]byte, 512)
)
pLength, err := c.KCPConn.Read(buf)

if pLength != 0 {
	var b []byte = make([]byte, pLength)
	copy(b, buf[:pLength])
	c.PacketChan <- b
}
```

I wanna avoid copy function. And with (30 packets / sec) memory growing up fast with only one call
`c.KCPConn.Read(buf)`
or this is normal behavior and way to catch packets?

also I tried byte[] pool, same issue with memory

**Comment by xtaci** [comment]
you can make use of `sync.Pool`   see `xmitBuf` in sess.go for example

**Comment by Dethrail** [comment]
sync.Pool works better than I found :) 

in your case with smitBu, you already know which size need from poll, there is way to know size of arrived packet? 

Thank you, for answering on my newbie questions and you are helping me a lot. 

I wrote you at mail some time ago. Did you receive?
