### ISSUE TITLE
Should we bump this package version to v5.6.13?

### ISSUE THREAD

**Issue by KatyushaScarlet** [xtaci/kcp-go#271]
Some open-source projects ([such as frp](https://github.com/fatedier/frp/pull/4367#issuecomment-2268056306)) prefer to import stable versions rather than the latest commits.
I believe that adding support for loong64 might worth a minor version bump for this package, making it more appealing for developers in the open-source community to using it on the new architecture.
Thanks!

**Comment by xtaci** [comment]
v5.6.13 pushed
