### ISSUE TITLE
License for image files

### ISSUE THREAD

**Issue by rogers0** [xtaci/kcp-go#28]
Hi there,

Thanks for working on this project.
I'm going to package this to Debian. However, according to rule of Debian, every file should be cleared in license.
So I'm writing to you to double confirm the following file:
 donate.png frame.png kcp-go.png shannon.jpg

Are you created the above 4 files by yourself? If so, we can safely treat it same as the code you wrote, so it's MIT/Expat license.
But if you borrow some files from other project, please let me know. So I can trace the license of each image file.
Thank you!

Cheers,
Roger

**Comment by xtaci** [comment]
thanks.

shannon.jpg comes from http://www.gettyimages.com/license/92926328 for non-commerical use.

others images are created by myself.
