### ISSUE TITLE
是否需要检测 buf 长度

### ISSUE THREAD

**Issue by kitech** [xtaci/kcp-go#29]
kcp.go:180   seg.data = xmitBuf.Get().([]byte)[:size]

这儿是怎么确保  xmitBuf.Get().([]byte) 长度 >= size 来生成新的 slice 吗？

我碰到几次在这行 crash，不过后来查了下是输入了异常的数据包导致的，不知道算不算是个bug。

**Comment by xtaci** [comment]
mtuLimit = 2000
