### ISSUE TITLE
High CPU usage upon connection breaking caused by timers

### ISSUE THREAD

**Issue by AudriusButkevicius** [xtaci/kcp-go#30]
See: https://github.com/syncthing/syncthing/pull/3489#issuecomment-279135064

I hope to have a more concise repro, but if you have any ideas that would be awesome.

**Comment by xtaci** [comment]
I'm trying to figure out the following: 

1. are you using my latest commits, I've fixed many *BufferBloat" related problem last month. It's very important for lower retransmission, and indirectly, retransmission drags CPU to pit.

2. > 3000 connections, setting `-interval` with `SetNoDelay` to 33 seconds cost 20% CPU according to my benchmark, I mean , by increasing interval value, CPU will be dramatically reduced.

**Comment by AudriusButkevicius** [comment]
In this case we are running with 10ms update interval, and a single connection, yet it still pegs a core.
I'll update the dependency as well to see what happens.

**Comment by xtaci** [comment]
yes, please update first, many optimizations have done last month.
