### ISSUE TITLE
In xor.go fastXORWords(), why perform xor in 8-word batch?

### ISSUE THREAD

**Issue by yydcool** [xtaci/kcp-go#31]
Hi, I just can't understand why xor 8 words in a batch?
> 	for i := ex; i < n; i += 8 {
> 		_dw := dw[i : i+8]
> 		_aw := aw[i : i+8]
> 		_bw := bw[i : i+8]
> 		_dw[0] = _aw[0] ^ _bw[0]
> 		_dw[1] = _aw[1] ^ _bw[1]
> 		.......
> 	}

Why not this:
> 	for i := ex; i < n; i += **1** {
> 		dw[i] = aw[i] ^ bw[i]
> 	}
Just a little explanation would help, compiler optimization? cpu pre-fetch? loop unrolling?

**Comment by xtaci** [comment]
loop unrolling, see https://en.wikipedia.org/wiki/Duff's_device
