### ISSUE TITLE
Bind local port for remote connection

### ISSUE THREAD

**Issue by ValdikSS** [xtaci/kcp-go#36]
Hi, it would be nice to see an option to bind local port in a client for a remote connection in `DialWithOptions` function.
Binding outgoing UDP socket for explicit port number is helpful for NAT traversal.
Please add an argument for `DialWithOptions` function and pass it to `DialUDP` second argument.

**Comment by AudriusButkevicius** [comment]
DialWithOptions takes a PacketConn as one of the arguments

**Comment by ValdikSS** [comment]
I mean https://github.com/xtaci/kcp-go/blob/master/sess.go#L914
Instead of "nil" in second argument there should be a way to specify source address and port.

**Comment by AudriusButkevicius** [comment]
This would be a breaking API change.

Just use NewConn(hostname:port, nil, 0, 0, your own provided PacketConn)

**Comment by xtaci** [comment]
@ValdikSS use your own net.PacketConn will solve this .
