### ISSUE TITLE
Getting 99% cpu usage, not sure what Im doing wrong

### ISSUE THREAD

**Issue by Bl4cksunLtd** [xtaci/kcp-go#37]
As the title suggests, I might be doing something wrong but currently kcp is not usable for how I am trying to use it.
Running a web server with kcp as the transport. Connecting to it works fine except once a client connects, the server continues to consume 99% cpu even if all clients disconnect. Doesn't seem to matter how much traffic is sent through the server.
based on the stated fact that kcp is "Compatible with net.Conn and net.Listener, easy to use",
My code is:
 
lis,err:=kcp.ListenWithOptions(addr,nil,10,3)
//	lis,err:=net.Listen("tcp",addr)
if err!=nil	{
	log.Fatal("Backend failed to listen on: ",addr)
}
srv:=&http.Server{Addr: addr, Handler: proxy}
log.Fatal(srv.Serve(lis)) 

switching back to the tcp transport in the above code resolves the issue with the cpu usage, the cpu usage is low when handling requests and drops to 'nothing' when the clients disconnect.
Is there some default settings that might be causing this? If so do you have a way to change them easily without needing to access the individual connection objects?
Cheers for any help that can be offered.

**Comment by xtaci** [comment]
can you show the full client/server demo code?

**Comment by Bl4cksunLtd** [comment]
Thanks Xtaci for responding so quickly. I am using the github.com/elazarl/goproxy package. It provides a proxy object which is a `net/http` handler. (I have also tried the github.com/abourget/goproxy package with the same result).
The main parts of the program are as follows(ip addresses/ports replaced with xxx and yyy)

package main

import (
	"flag"
	"time"
	"log"
	"net/http"
	"net/url"
	"net"
	kcp "github.com/xtaci/kcp-go"
	"github.com/elazarl/goproxy"
)
func main() {
	verbose := flag.Bool("v", false, "should every proxy request be logged to stdout")
	addr := flag.String("addr", ":yyyy", "proxy listen address")
	raddr := flag.String("remote", "http://xxx.xxx.xxx.xxx:yyyy", "remote proxy listen address")
	backend:= flag.Bool("backend",false,"Run as backend proxy")
	flag.Parse()
	proxy := goproxy.NewProxyHttpServer()
	proxy.Verbose = *verbose
	if !*backend	{
		ProxyUrl,_:=url.Parse(*raddr)
		proxy.Tr=&http.Transport{	
				Dial:	func(network, addr string)(net.Conn, error){
							return kcp.DialWithOptions( addr,nil,10,3) }	,
				Proxy:func(req *http.Request)(*url.URL, error) { return	ProxyUrl ,nil}}
		log.Println("Client listening to :",*addr)
		log.Println("       sending to   :",*raddr)
		log.Fatal(http.ListenAndServe(*addr,proxy))
	}	else	{
		log.Println("Backend listening to :",*addr)
		lis,err:=kcp.ListenWithOptions(*addr,nil,10,3)
		if err!=nil	{
			log.Fatal("Backend failed to listen on: ",*addr)
		}
		srv:=&http.Server{Addr: *addr, Handler: proxy}
		log.Fatal(srv.Serve(lis))
	}
}	
The above doesnt work with https connections (it needs extra code and certificates) so I've been using http://httpbin.org/html to test. Page loads correctly but the backend continues to use 99% CPU even if I stop the client after the page is loaded.

**Comment by xtaci** [comment]
I've found the problem, you can upgrade to the latest commits, OR, calling 

`SetNoDelay()` once on both client & server

**Comment by Bl4cksunLtd** [comment]
That's sorted the problem. Thank you so much for the speedy fix, support and excellent package.
