### ISSUE TITLE
add one api for kcp-go version

### ISSUE THREAD

**Issue by sheepbao** [xtaci/kcp-go#44]
I want a api to get kcp-go version, It is easy to implement .Thanks

**Comment by xtaci** [comment]
govendor or glide can easily download given version or upgrade. all versions are released under :
https://github.com/xtaci/kcp-go/releases

**Comment by sheepbao** [comment]
Thanks, I want to print kcp-go version in my program.

**Comment by xtaci** [comment]
You need to use some injection technique at compiling time, such as 

go build -ldflags "-X main.kcpversion=v3.9"

**Comment by sheepbao** [comment]
这样当然是可以的，但是这样每次的版本得我自己控制了，希望的是直接获取kcp库的版本，谢谢

**Comment by xtaci** [comment]
用脚本编译很容易就获得了，直接写到源码并不合适，这通常都是由编译过程动态注入的。

方法1. git获取当前tag
方法2. govendor ／glide 获取当前tag

**Comment by sheepbao** [comment]
嗯嗯，我看到很多库都是在源代码写版本库的，因为对于库管理，版本很重要，谢谢回答
