### ISSUE TITLE
UDP to KCP Connection Upgrade

### ISSUE THREAD

**Issue by BourgeoisBear** [xtaci/kcp-go#46]
If I have already established a net.UDPConn connection (like a UDP rendezvous for example), and want to upgrade that to a KCP connection, is there a way to do that with the library as-is, or would it require a new function?

Also, noticed that the Set(Read/Write)Deadline functions for Listener and UDPSession don't update the deadlines for the underlying connection (so if the inherited connection already had a deadline set, the Listener/UDPSession calls will not reset it).  

What am I missing here?

Thanks!

**Comment by paralin** [comment]
Also need this, so that I can handshake the protocol before continuing.

**Comment by BourgeoisBear** [comment]
@paralin I upgraded my established UDP connection by pre-selecting one side to be the listener and one side to be the dialer.  On the listener side, I make a call to ServeConn.  On the dialer side I make a call to NewConn.  For both, I pass in the pre-established UDPConn as the last parameter.

It's not ideal, but it solved my problem.

**Comment by stwiname** [comment]
@BourgeoisBear how do you get a UDPSession after calling ServeConn?

**Comment by BourgeoisBear** [comment]
@stwiname give me a day to dig that up.

**Comment by BourgeoisBear** [comment]
Since I pre-designate one side to be the listener, the way it is done depends on which side I am:

```go

oPConn, oErr := net.DialUDP("udp", oSelf, oPeer)
ERR_EXIT(oErr)

// ... CONFIGURE BLOCK CRYPTO (oCipher, DataShard, ParityShard)

if /* LISTENER */ {

    var oKCP *kcp.UDPSession
    oListen, oErr := kcp.ServeConn(oCipher, DataShard, ParityShard, oPConn)
    ERR_EXIT(oErr)
    defer oListen.Close()

    oErr = oListen.SetReadBuffer(SockBuf)
    ERR_EXIT(oErr)

    oErr = oListen.SetWriteBuffer(SockBuf)
    ERR_EXIT(oErr)

    oErr = oListen.SetDeadline( time.Now().Add( time.Second * 10 ) )
    ERR_EXIT(oErr)

    oKCP, oErr = oListen.AcceptKCP()
    ERR_EXIT(oErr)

} else { /* INITIATOR */

    oKCP, oErr = kcp.NewConn(oPeer.String(), oCipher, DataShard, ParityShard, oPConn)
    ERR_EXIT(oErr)

    oErr = oKCP.SetReadBuffer(SockBuf)
    ERR_EXIT(oErr)

    oErr = oKCP.SetWriteBuffer(SockBuf)
    ERR_EXIT(oErr)

}
```
