### ISSUE TITLE
kcp本地测试也会出现重传包

### ISSUE THREAD

**Issue by sheepbao** [xtaci/kcp-go#48]
用kcp-go写了client和server端，都在本地运行，client从/dev/zero读取数据发送给server端，server端接收数据后丢弃，但是更据snmp的统计数据，client端出现重传，好奇为啥会出现重传包，在本地应该不至于ack会丢失啊。kcp参数设置关闭了拥塞控制，关闭了快速重传。

**Comment by xtaci** [comment]
rtt收敛需要时间

**Comment by sheepbao** [comment]
我试了一下，把发送和接收的窗口大小设置的小点就不会出现重传，而窗口设置的大一点，就会重传，估计是窗口大了导致snd_buf过大，而发送的慢，导致重传。 而且我调节各种参数后，本地重传的速度最大为550Mbit/s，和tcp 4Gbit/s 差距挺大的。
