### ISSUE TITLE
有更快的 rs 引擎可以替代 github.com/klauspost/reedsolomon

### ISSUE THREAD

**Issue by templexxx** [xtaci/kcp-go#49]
地址如下：
https://github.com/templexxx/reedsolomon

**Comment by xtaci** [comment]
是否能做一个兼容klauspost的接口？wrap一下现有的。

**Comment by templexxx** [comment]
@xtaci 可以的  

等弄好了，我继续在这里更新状态

**Comment by xtaci** [comment]
好的，希望有一个和klauspost的 横向对比

**Comment by jannson** [comment]
来顶一个。

**Comment by phpstudyer** [comment]
暗中观察

**Comment by templexxx** [comment]
@xtaci 应该 okay 了

**Comment by templexxx** [comment]
@xtaci 做了个 benchcmp
![snip20170903_1](https://user-images.githubusercontent.com/13476726/30003919-36cc5c1a-90f8-11e7-9443-1ccac5953b9a.png)
