### ISSUE TITLE
sess的SetKeepAlive这个函数没有了?

### ISSUE THREAD

**Issue by zhuwei** [xtaci/kcp-go#56]
func (s *UDPSession) SetKeepAlive(interval int)
为什么啊? 有其他说明代替的吗?

**Comment by zhuwei** [comment]
怪事, 以前的版本很稳定, 更新到最新版本后
几秒钟就出现i/o timeout

**Comment by xtaci** [comment]
you should do it in application-level, such as  a ping/pong command, like what smux does.

**Comment by zhuwei** [comment]
thank you very much!
