### ISSUE TITLE
About dependency library reedsolomon

### ISSUE THREAD

**Issue by rogers0** [xtaci/kcp-go#57]
I'm debian pkg maintainer of a few kcp related projects.
It's got my attention that golang-github-xtaci-kcp v3.19 changes dependency library reedsolomon from original upstream to a fork, which claims big performance boost:
 - https://github.com/templexxx/reedsolomon

So for debian pkg maintainer, before I can release debian pkg of  golang-github-xtaci-kcp to v3.19, I have to package the new fork of reedsolomon, which I want to avoid.
So I created ticket to the fork and upstream, to seek the possibility of merging 2 version.
 - https://github.com/templexxx/reedsolomon/issues/9
 - https://github.com/klauspost/reedsolomon/issues/69

Now it seems the author of the fork isn't interested to submit the improvement patch upstream.
However the original author replied in detail and proposed his improvement:
 - https://github.com/klauspost/reedsolomon/pull/70

So I want to ask whether it's possible for you, golang-github-xtaci-kcp, to change back to the original upstream of reedsolomon, of course with the patch in pull-request above.

Thanks for your understanding!

Cheers

**Comment by xtaci** [comment]
@templexxx

**Comment by templexxx** [comment]
@rogers0 

I made some tricks for cache-friendly, so it will make performance improving when the shards size is big or the size can't divisible by 16 or the size is very small ( < 4KB)

maybe you can run the bench by yourself and you will find the difference.

But the cores of the two RS lib are same as klauspost said.

**Comment by rogers0** [comment]
@xtaci 
After reading https://github.com/klauspost/reedsolomon/issues/69, I think the fork of @templexxx has just minor improvement on single-core system, while the original upstream has far better result on multi-core system. There may be some other improvement in the fork, but the upstream already started to adopt it recently, https://github.com/klauspost/reedsolomon/pull/70.

So I think for golang-github-xtaci-kcp, it's still better keep the original upstream, https://github.com/klauspost/reedsolomon.
Maybe it's easier for you to do the transition after https://github.com/klauspost/reedsolomon/pull/70 get merged.
Or you have some other plan?
Thanks!


@templexxx
Thank you very much for your nice work!
If you have more improvements, it's appreciated if you could send them upstream.

Cheers,
Roger

**Comment by xtaci** [comment]
@rogers0 sure, cool, I'll import the fastest one, if klauspost's version exceeds @templexxx's

i think it's better to cooperate with the klauspost @templexxx , how do you think about this, is there any design flaw that cannot be circumvented in klaus's architecture?

**Comment by templexxx** [comment]
@rogers0 Actually, I think one reed-solomon job one core is better than one job on multi-cores. It will reduce the race in CPU. And it's easy to make multi-jobs run on multi-cores. In many High Performance Computing practice, we do things in my way, and we will turn off the hyper-threading too.

For kcp-go, the size of each shards always  can't divisible by 16 or 32, it means some bytes can't use SIMD to improve performance, and if you calculate it in base way (look up multiply tables), it will pollute the CPU cache too.

that's the bench run on my laptop:
![snip20170903_1](https://user-images.githubusercontent.com/13476726/30003919-36cc5c1a-90f8-11e7-9443-1ccac5953b9a.png)

@xtaci  klauspost/reedsolomon & mine have same API, so we can do same things. 

Anyway, I think it's ok to keep klauspost/reedsolomon, rs codes it's not the bottleneck in this system

**Comment by xtaci** [comment]
@templexxx @rogers0 I will support the fastest one in my system, performance has improved based on tests, but SIMD compatibility is a problem in current version.

when will you release a fix to this?

**Comment by templexxx** [comment]
@xtaci I have fixed it

**Comment by xtaci** [comment]
@templexxx the tag please

**Comment by templexxx** [comment]
@xtaci [https://github.com/templexxx/reedsolomon/tree/0.1.1](url)

**Comment by rogers0** [comment]
@templexxx thanks for pushing your improvement upstream!
If you think your changes superior to upstream, you should persuade the upstream to accept your changes.

Since upstream is quite active, I don't think it deserve a fork for debian.
You really should upstream your code, rather than persuading the user, such as kcp, to use your fork.
Thanks for your understanding!

**Comment by xtaci** [comment]
any progress on the upstream? @templexxx @rogers0

**Comment by rogers0** [comment]
@xtaci https://github.com/klauspost/reedsolomon/issues/69
upstream tested and the result is:
 - for single thread case, there's not much difference between klauspost and @templexxx implementation
 - for multi-thread case, klauspost's version is much faster

So I don't think debian should have another forked package for reedsolomon, and I'd like to recommend you to switch back to klauspost's version.
Thanks!

**Comment by xtaci** [comment]
@rogers0 OK I'm gonna switch back to klaus's version, but I'll keep @templexxx 's xor module

**Comment by rogers0** [comment]
@xtaci thanks for your understanding!

@templexxx could you kindly help to upstream your xor module?

**Comment by templexxx** [comment]
@rogers0 sorry, I'm a little confused, where should I upstream my xor module? :D

**Comment by xtaci** [comment]
@rogers0 you misunderstood that, i mean https://github.com/templexxx/xor/

**Comment by rogers0** [comment]
@xtaci @templexxx I see. Now I understand it's necessary to package xor and gmsm for debian. Because it's kcp's new dependency.
I'm closing this ticket. Thanks for your patience!

**Comment by xtaci** [comment]
@rogers0 @templexxx thanks for both of you.
