### ISSUE TITLE
cpufeat这个库会用不支持的指令

### ISSUE THREAD

**Issue by vinsia** [xtaci/kcp-go#58]
# github.com/templexxx/cpufeat
src/github.com/templexxx/cpufeat/cpu_x86.s:28: unrecognized instruction "XGETBV"
asm: asm: assembly of src/github.com/templexxx/cpufeat/cpu_x86.s failed

**Comment by xtaci** [comment]
@templexxx

**Comment by templexxx** [comment]
@vinsia I think it will be ok now

I use" WORD $0x010f; BYTE $0xd0 instead of WORD" instead of "XGETBV" now

by the way, what's your go version? go1.5?

**Comment by vinsia** [comment]
@templexxx yeah, the version is 1.5.2

**Comment by templexxx** [comment]
@vinsia  现在okay了吧

**Comment by vinsia** [comment]
# github.com/templexxx/xor
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:42: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:43: unrecognized instruction "VPXOR"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:44: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:48: unrecognized instruction "VZEROUPPER"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:101: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:102: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:103: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:104: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:105: unrecognized instruction "VPXOR"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:106: unrecognized instruction "VPXOR"
../../../../go/src/github.com/templexxx/xor/avx2_amd64.s:107: unrecognized instruction "VPXOR"
asm: too many errors
# github.com/templexxx/reedsolomon
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:44: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:45: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:48: unrecognized instruction "VPBROADCASTB"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:54: unrecognized instruction "VINSERTI128"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:55: unrecognized instruction "VINSERTI128"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:56: unrecognized instruction "VINSERTI128"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:65: unrecognized instruction "VMOVDQU"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:66: unrecognized instruction "VPSRLQ"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:67: unrecognized instruction "VPAND"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:68: unrecognized instruction "VPAND"
../../../../go/src/github.com/templexxx/reedsolomon/rs_amd64.s:69: unrecognized instruction "VPSHUFB"
asm: too many errors

**Comment by vinsia** [comment]
@templexxx 更多了

**Comment by templexxx** [comment]
@vinsia 

我的锅。。 忘记 rs 部分的指令了

go1.5 确实支持的指令比较少。。

**Comment by vinsia** [comment]
我upgrade一下golang是不是就行？

**Comment by templexxx** [comment]
@vinsia 是的
