### ISSUE TITLE
fec问题

### ISSUE THREAD

**Issue by dista** [xtaci/kcp-go#63]
关于fec decode, 感觉跑了一段时间会有问题
假设一开始seqid是一直增长的， data_shards是2， parity_shards是1，
1. 假设先收到0, 1, 然后解析成功,  0, 1从queue里面去掉了
2. 收到2, 那么2就会留在queue里面
3. ... 假如1，2两步一直重复， 那么queue就会被填满
4. seqid一直增， 直到超过最大值，然后从0重新开始， 从这个时间开始， 因为queue满了， 
而新的seqid一直小于queue里面的数值，  这样最小的seqid就会被淘汰， 那样的话，从这个点开始,fec就相当于一直不工作了.

**Comment by xtaci** [comment]
``` 
90 func _itimediff(later, earlier uint32) int32 {
 91     return (int32)(later - earlier)
 92 }
 93
```

**Comment by dista** [comment]
哈， 没注意这个trick.

**Comment by dista** [comment]
还有个fec和ikcp结合的问题， 不是很确定是否有问题:
我看现在里面的kcp.go对ikcp.c进行了些修改， 对于fec解析出来的ack包，不用做算rtt.

但是对于PUSH包，没做特别处理
假设下面这种情况 

1. data_shards: 2, parity_shards: 1
2. A 发送了 sn为1, 2, 3的push包(3个push包在1个fec data包里面, 假设seqid是1),    该fec data包前面还有个seqid为0的data包， 后面有个seqid为2的parity包，   假设这0，2的fec包因为丢包，花了2秒B才收到， 而1在0, 2收到的时候， 还是没收到， 那么 fec就会恢复出seqid为1的包
3. B kcp.go会对PUSH 发个 ack包， 假设这个ack包A收到了(直接收到了，不是通过fec恢复的)， 那么在A那边就会用这个ack包去算rtt, 这样算出的rtt就会大于2秒， 那样的话，接下去A发的几个包就会发的很慢

**Comment by xtaci** [comment]
既然是花了两秒才收到，那就不是丢包啊，那就是网络慢了。就应该判断为2秒。

**Comment by xtaci** [comment]
另外，这里有个假设，sender:PARITY包是由sender:DATA包的产生触发的，那么，receiver:ACK发送的时候，`只需要用这一批次最后一个数据包ACK`（不管这个数据包是原始的，还是还原出来的），这最后一个数据包一定等价于PARITY包收到的时间，也就是说，无论如何，都不会因为ACK一个FEC还原出来的DATA包，导致RTT计时偏差。

参考:
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L644

**Comment by dista** [comment]
我是用c版本的ikcp里面的test.cpp跑的测试， 加了fec, 原来跑100秒的case, 跑了200秒， 然后我把fec decode出来的PUSH的ack加上特殊标记，让对方不算rtt, 就<100秒了。感觉像是累积到了2s, 但是具体是什么样的包序列， 我再debug看看

**Comment by dista** [comment]
不知道我理解的对不对。 
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L548     这个返回的ack ts应该就是push包的ts,  这个ack包发给对方后， 对方算出来的rtt可能是带fec延迟的

**Comment by xtaci** [comment]
C语言版本的需要做不少修改，才能正确处理RTT

**Comment by xtaci** [comment]
我上面已经说了

https://github.com/xtaci/kcp-go/blob/master/kcp.go#L644
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L585


仔细想想，为什么不会有FEC延迟。读不懂就反复读几遍。

**Comment by dista** [comment]
哈， 多谢。我再仔细研究下

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/kcp.go#L545

这个变量 和 https://github.com/xtaci/kcp-go/blob/master/kcp.go#L641

多想想

**Comment by xtaci** [comment]
刚提交了一点，这样应该更准确。

**Comment by dista** [comment]
有些情况我感觉上面的说的不能cover.

```
if ack.sn >= kcp.rcv_nxt || len(kcp.acklist)-1 == i {
  ...
}
上面这行， 如果sn < kcp.rcv_nxt, 但是acklist长度是1也是能发出去的
``` 

假设, data shards是3， parity shards是1,  data shards标号分别是0, 1, 2,  parity shards为3
0 里面装的内容无所谓， 1里面装的是sn为10的PUSH segment, 2里面装的是sn为10的ACK(2和1中间隔了xx ms), 3是parity数据.

如果1丢失了， 导致重传了几次， 最后重传的都没收到，  0, 2都马上收到了， 在重传过程中， 上层没有再下发数据， 所以没有新包产生,  3也丢了几次， 3最后收到了,   通过0, 2, 3会恢复出1， 1里面sn为10的 PUSH segment产生了1个ts为PUSH包ts的 ack包，     因为acklist长度是1, 所以这个包能发出去.

对方收到了ack包， 计算rtt就     =      current - ts,   因为中间重传了几次， 会算出1个比较大的值

**Comment by xtaci** [comment]
3是parity，意味着，3是2发出去后，满足 3:1 立即发送出去的parity shard，不会有单独的parity shard过了一段时间再收到。3不会丢了几次，parity丢了就是丢了，不存在丢几次这回事，FEC没有重传。

**Comment by dista** [comment]
fec parity不会重传是我忽略了， 我再想想。

**Comment by dista** [comment]
接上面的情况， 
3丢了(fec parity)， 1也丢了，0, 2收到了,   然后接着会重传1(sn为10的push包),  重传的fec标号为
4,  B没有收到4， 然后A再重传, fec标号为5， B这个时候收到了， 但是ack包 A没有收到，  A会继续重传
标号为6, 同时也会发送标号为7的parity.  标号6 B收到了， 

那么在B的fec queue里面， 就存在  5, 6, 7, 那么就会解出4,        4里面只有1个PUSH包， 会触发发送ack包(acklist=1), 
这样A算出的rtt就是 current - 4的ts, 这样也比较大

**Comment by xtaci** [comment]
错了，一旦A重传了， 那么数据包的时间也更新了， ack后，不会更大。

**Comment by dista** [comment]
时间是会更新， 但是4的ts是它重传的时候的ts,  等发到7的时候， 已经过了2个rto了， 然后用current - 4的ts就比较大

**Comment by xtaci** [comment]
4的ts在发送端，已经更新了。

**Comment by dista** [comment]
发送端对于sn为10的ts更新， 不会影响计算。  现在参与计算的是返回给A的ack包ts1(也就是接收到的4的ts1, 不是当前发送端那个ts2)

**Comment by xtaci** [comment]
current -ts < 0 ，丢弃，因为current时间已经往后了。

**Comment by dista** [comment]
current - 返回给A ack里面的ts1 是  > 2rto的, 不会被丢弃吧， 会被用做更新rto

**Comment by xtaci** [comment]
A端：RTO导致   ts = ts+rto ，即ts变大
B端：ACK的包，要么是ts,要么是ts+rto 


那么在A端，  时间为： current - ts  或者 current -(ts+rto)

**Comment by dista** [comment]
没fec是这样的， 但是上面说的情况， ack的是4的ts1, 那个ts1是在2个rto之前就发了（只是没收到， 后来通过fec恢复了）

**Comment by xtaci** [comment]
不管你怎么ack， ack的无非就是 ts, ts+rto , ts+2rto...... ts+nRTO这些值
A端KCP内部：ts单调递增，  也许你ack的是ts， 但A端的内部seg.ts == ts+nRTO了

**Comment by dista** [comment]
A端的内部seg.ts又不参与计算rto.

```
        		kcp.parse_ack(sn)
			kcp.shrink_buf()
			if flag == 0 {
				flag = 1
				maxack = sn
				lastackts = ts
			} else if _itimediff(sn, maxack) > 0 {
				maxack = sn
				lastackts = ts       // 这个ts从ack包里面解析出来的
			}


        ...

	if flag != 0 && regular {
		kcp.parse_fastack(maxack)
		current := currentMs()
		if _itimediff(current, lastackts) >= 0 {
                        // 计算rto也是通过上面那个ts, 不是通过A端内部seg的ts
			kcp.update_ack(_itimediff(current, lastackts))
		}
	}
```

参与计算的4那个ack包里面的ts

**Comment by xtaci** [comment]
嗯，貌似有点问题，我试下

**Comment by xtaci** [comment]
如果ack包是从FEC还原过来的，那么
582     if flag != 0 && regular { 
这里就不会参与计算

**Comment by dista** [comment]
PUSH包是从fec还原的， ack包不是， ack是对还原的PUSH包做的（本身不是fec还原的），   发到A端的时候， regular是1

**Comment by xtaci** [comment]
537             kcp.parse_ack(sn)
如果让已经ack过的，不参与rtt的计算，是不是就能解决你所说的这种情况

**Comment by dista** [comment]
好像不行， 4那个PUSH包之前并没有ack过.  5, 6发的ack包都丢了， 所以4那个ack包是它收到的第1个对应那个PUSH的ack包。 
我现在是对fec解析出的PUSH包 返回的 ack包，带个特殊标记， 对方看到特殊标记就不用它计算rtt了（我不是100%觉得这种方法好），想听听你对这个问题有没有更好的办法

**Comment by xtaci** [comment]
如果4是第一个PUSH包，第一个ack包，那么他的时间就应该是正确的，就是首次成功传输的时间。

**Comment by dista** [comment]
但是如果没有fec, 它应该是用的 6以后重发 包的 ack算得rto，假设是8吧， 这个rto就是正常的kcp的rto.
我跑了下不加fec的case,   尽管都是模拟的60%的丢包， 不会因为丢包导致rto变的这么高的. 那个case跑了100秒， 加了fec反而跑了200秒。

**Comment by xtaci** [comment]
你的测试应该是小数据，低频的吧，才会产生间隙

**Comment by dista** [comment]
是的， 也许实际情况下， 出现这样情况的几率不高

**Comment by xtaci** [comment]
小数据也是一个问题，交互式的少量数据+高丢包率，确实有一定可能导致rto算大了。
要满足的条件是：
1. 产生parity的最后的datashard包，没有成功发送ack
2. 并且这个parity还原了sn比最后的datashard内的sn还小的一个包
3. 这个sn包是上一轮发送的的，有一定时间延迟。

**Comment by xtaci** [comment]
这个问题我想了一下，其实有个跟简单的表述，  ACK包的delayed replay-attack，会导致rtt过高降速
