### ISSUE TITLE
Question about kcp under high load (sort of high load)

### ISSUE THREAD

**Issue by pvva** [xtaci/kcp-go#70]
Hi, 
I'm trying to use kcp to speed up data transmition over network. I will post example code, that I'm using to simulate data transfer.

Common part
```go
func configureKCPConnection(conn *kcp.UDPSession, timeout time.Duration) {
	conn.SetStreamMode(true)
	conn.SetWindowSize(512, 512)
	conn.SetNoDelay(1, 40, 2, 1)
	conn.SetACKNoDelay(false)

	conn.SetReadDeadline(time.Now().Add(timeout))
	conn.SetWriteDeadline(time.Now().Add(timeout))
}

func recvData(r io.Reader) ([]byte, error) {
	buf := make([]byte, 4)

	_, err := r.Read(buf)
	if err != nil {
		return nil, err
	}

	if len(buf) == 0 {
		return buf, nil
	}

	// read message size as 4 bytes from the beginning of the message
	size := int(binary.LittleEndian.Uint32(buf))

	mbuf := bytes.NewBuffer([]byte{})

	buf = make([]byte, 4096)

	total := 0
	for total < size {
		n, err := r.Read(buf)
		if err != nil {
			return nil, err
		}
		mbuf.Write(buf[:n])
		total += n
		if err != nil {
			break
		}
	}

	return mbuf.Bytes(), nil
}

func sendData(w io.Writer, msg []byte) (int, error) {
	b := []byte{0, 0, 0, 0}
	binary.LittleEndian.PutUint32(b, uint32(len(msg)))

	mbuf := bytes.NewBuffer(b)
	mbuf.Write(msg)

	return w.Write(mbuf.Bytes())
}
```

Server:
```go
const symbols = " 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

func generateRandomText(size int) string {
	b := make([]byte, size)
	for i := range b {
		b[i] = symbols[rand.Int63()%int64(len(symbols))]
	}
	return string(b)
}

func main() {
	l, err := kcp.ListenWithOptions("0.0.0.0:8100", nil, 10, 3)
	if err != nil {
		panic(err)
	}
	defer l.Close()

	timeout := time.Second * 30

	fmt.Println("running...")
	for {
		conn, err := l.AcceptKCP()
		if err != nil {
			fmt.Println(err)
			continue
		}

		configureKCPConnection(conn, timeout)
		msg, err := recvData(conn)
		if err != nil {
			fmt.Println(err)
		} else {
			fmt.Println("received:", string(msg))
		}

		n, e := sendData(conn, []byte(generateRandomText(131072)))

		if e != nil {
			fmt.Println(e)
		} else {
			fmt.Println("wrote", n, "bytes")
		}

		conn.Close()
	}
}
```

Client:
```go
func main() {
	limit := 10

	for i := 0; i < limit; i++ {
		conn, err := kcp.DialWithOptions("remote_ip_addr:8100", nil, 10, 3)

		if err != nil {
			panic(err)
		}

		timeout := time.Second * 30

		configureKCPConnection(conn, timeout)

		sendData(conn, []byte("hello"))
		msg, err := recvData(conn)

		if err != nil {
			fmt.Println(err)
		} else {
			fmt.Println("message size recevied is", len(msg))
		}

		conn.Close()

		time.Sleep(time.Millisecond * 100)
	}
}
```

When `limit` in client is 1, everything is perfect, single transmission works very well.
When `limit` is more than 1 (10, 50, 100, 500, 1000 and so on), client periodically times out, as well as server. Timeouts happen on `conn.Read` (`r.Read` in the code of `recvData` method)

Questions:
- do I use kcp correctly, assuming it provides reliability over udp for single client? 
- what should I do not to have timeouts?

**Comment by xtaci** [comment]
you can try smux .

multiple concurrent kcp conn battles for bandwidth, it's not recommended.

**Comment by varyukhichev** [comment]
I have independent clients, how can smux help me? I have tried it, but without luck, it report "broken pipe" instead of "i/o timeout".

**Comment by varyukhichev** [comment]
Anyway, even for a single client, which does requests sequentially, I have timeouts. What about that?

**Comment by xtaci** [comment]
independents  clients should first connect with tcp relay node, and mux with smux and ship with kcp connection to remote.

**Comment by xtaci** [comment]
independents clients in direct connections in kcp should adjust window to a smaller value , to avoid congestion

**Comment by varyukhichev** [comment]
Played around with window size (from 4 to 128, different values), without much luck.
But smux... do I understand correctly that client first connects to some local node (proxy?) and this node has single kcp connection with remote host and does all data transmission? Does it mean that remote host also has such "node", that provide kcp connection for clients (multiplexed) and has multiple tcp connections with locally running server?

**Comment by xtaci** [comment]
write to a stream and reading from stream should be in two different goroutine, a blocking in write or read will cause deadlock in a single goroutine when window of both sides are full

**Comment by varyukhichev** [comment]
Well, still if a message size is quite big, then there are a lot of timeouts.

**Comment by varyukhichev** [comment]
If you would have a solution when multiple clients communicate with server and transferring large chunks of data (128k and more), please share it with me. If not, you can just close this question.

**Comment by paralin** [comment]
@AudriusButkevicius you can just simply open a smux stream and then use io.Copy to copy some data over... :)

**Comment by AudriusButkevicius** [comment]
Sorry, why am I being pulled into this?

**Comment by paralin** [comment]
@AudriusButkevicius Haha, sorry. I was trying to tag @varyukhichev but didn't notice the tab completion selected the wrong person.
