### ISSUE TITLE
请教下发文件时过了几秒就阻塞了

### ISSUE THREAD

**Issue by zhuwei** [xtaci/kcp-go#78]
发了太频繁了?
把文件切成N片时, 每发一片就得等待接收端的回应,  是不是得这个样子?

**Comment by jannson** [comment]
肯定是你的代码错误，你这样说没人可以回答你，最好帖代码。
为何说肯定是你代码的错误？因为我用　kcp-go 传　n 个文件，同步整个文件夹都没问题。

**Comment by zhuwei** [comment]
@jannson 感谢回复！！不好意思这个我已经解决了，是我自己的逻辑问题，没有考虑过带宽，没有仔细阅读作者的说明
