### ISSUE TITLE
write: no buffer space available

### ISSUE THREAD

**Issue by smcduck** [xtaci/kcp-go#79]
mac 客户端   --上传文件-->   linux 服务端

我在同时增大发送端sndWnd和接收端rcvWnd的时候出现的write udp 10.168.1.100:58973->47.52.*。*:9099: write: no buffer space available，增大到超过大概800-1000左右的时候就会出现这个错误，具体数值还没有验证。

在启动之前，我已经在mac下执行过sudo sysctl -w net.inet.udp.maxdgram=65535了。

谢谢！🙏

**Comment by xtaci** [comment]
看下kcptun主页的rmem,mem调整
