### ISSUE TITLE
sessionKey冲突问题

### ISSUE THREAD

**Issue by jackerlu** [xtaci/kcp-go#85]
from.String()和conv作为sessionKey可能会出现冲突的情况，比如A和B在同一个局域网下，对外出口IP相同，A和B作为客户端连接C时，C得到A和B的地址是相同的(同一个公网地址)，而且A和B随机生成的conv也有可能相同，所以建议不应该由客户端随机生成conv，而是由服务端去分配conv，这样能够避免sessionKey冲突问题

**Comment by michaelyou** [comment]
from不只有ip，还有端口号
