### ISSUE TITLE
这里的切片在并发下可能出现问题

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#86]
https://github.com/xtaci/kcp-go/blob/42bc1dfefff592fdb3affa793980c4f6ab4213e5/fec.go#L167

这里的切片返回给上层了，但是下面又回收给池了 ，如果在上层没处理完别的地方做了修改的话可能会出现数据错乱的情况？

**Comment by xtaci** [comment]
能提供一个冲突的例子么

**Comment by l42111996** [comment]
我在照着这个写java版本的fec 感觉这里会有问题。

**Comment by xtaci** [comment]
如果只是感觉，那就不会
