### ISSUE TITLE
三次确认关闭协议?

### ISSUE THREAD

**Issue by bronze1man** [xtaci/kcp-go#9]
目前kcp-go协议相对于tcp协议缺少一个关闭协议,
当通讯一方A关闭了连接,通讯另一方B不知道A关闭了连接,B的连接会一直挂起到超时.
这个问题导致kcp协议难以作为代理协议取代 ss.

**Comment by xtaci** [comment]
请参考kcptun的实现， 通常，一条kcp连接是长链接，不会关闭， 你需要的是在一条链路上进行多路复用，比如用yamux。

1. 关于FIN的问题， 我觉得这个可以在上层协议实现。
2. 即使实现了FIN， 超时判定和心跳依然不可少，请参考 tcp_retries2参数作用。
3. yamux这种mux工具，本身带有心跳，超时，所以问题不大。

**Comment by bronze1man** [comment]
多谢.
之前用过  yamux这种mux工具来muxtcp连接 ,结果比多条tcp连接更不稳定了.

**Comment by xtaci** [comment]
我的实测结果还好，后端接入dante，速度通常能到1MB/s
