### ISSUE TITLE
关于sync.pool和chan的疑问

### ISSUE THREAD

**Issue by tobygz** [xtaci/kcp-go#92]
据我了解chan的入是深copy, 那1500这块内存目前的写法是不是没有起到应有的作用(至少是有优化空间), 是否更好的写法是 入chan和前后使用sync.pool呢? 

xmitBuf.Get().([]byte)[:mtuLimit]

**Comment by sheepbao** [comment]
你了解错了，入chan明显是浅copy，不信你可以试试

**Comment by tobygz** [comment]
谢谢...[]byte确实是浅copy
