### ISSUE TITLE
FEC should be optional

### ISSUE THREAD

**Issue by chenqinghe** [xtaci/kcp-go#93]
FEC should be optional, but fecDecoder and fecEncoder was set when called `newUDPSession`  no matter FEC was needed or not. KCP library in C is not support FEC by now, so the packet sent by client written by C will be ignored by server built with kcp-go. Is  there another way to create udpsession without FEC? thx.

**Comment by xtaci** [comment]
https://github.com/xtaci/kcp-go/blob/master/sess.go#L870

**Comment by chenqinghe** [comment]
@xtaci i see. to disable FEC, just **set `dataShards` and `parityShards` equal to 0**. thank you very much.
