### ISSUE TITLE
请教这段代码

### ISSUE THREAD

**Issue by l42111996** [xtaci/kcp-go#94]
https://github.com/xtaci/kcp-go/blob/ebb64e277a97926a288dc3b74d23f384159f2b63/kcp.go#L764
这段在c里面是没有的，是为了在空闲时候让需要重发的包更快的发出去吗？还有别的什么意义吗？

**Comment by jannson** [comment]
https://tools.ietf.org/html/rfc5827
可能这个文章对你有用。
群主的首页有介绍。

**Comment by l42111996** [comment]
理解了  谢谢
