### ISSUE TITLE
Is there any problem if change the system time?

### ISSUE THREAD

**Issue by jinq0123** [xtaci/kcp-go#98]
`currentMs()` uses time.Now().UnixNano() to get a timestamp, which is subject to changes for clock synchronization. 
```
// returns current time in milliseconds
func currentMs() uint32 { return uint32(time.Now().UnixNano() / int64(time.Millisecond)) }
```
Is there any problem if change the system time? Such as:
```
		} else if _itimediff(current, segment.resendts) >= 0 { // RTO
			needsend = true
```

**Comment by jinq0123** [comment]
I tested with kcp_test.go. I changed the system time back while testing in default mode, and the test took a very long time.

**Comment by xtaci** [comment]
time.Now() returns *monotonic clock"

**Comment by xtaci** [comment]
https://golang.org/pkg/time/

**Comment by jinq0123** [comment]
> time-telling operations use the wall clock reading

UnixNano() uses the wall clock. Test with code:
```
func main() {
	for {
		ms := time.Now().UnixNano() / int64(time.Millisecond)
		fmt.Printf("%d\n", ms)
		time.Sleep(time.Second)
	}
}
```

**Comment by xtaci** [comment]
```
// monotonic nanoseconds reference point
var refTime time.Time = time.Now()
var refUnixNano int64 = refTime.UnixNano()

// returns current time in milliseconds
func currentMs() uint32 {
    d := time.Now().Sub(refTime)
    return uint32((refUnixNano + int64(d)) / int64(time.Millisecond))
}
```

check if this fixed that issue?

**Comment by xtaci** [comment]
fixed in https://github.com/xtaci/kcp-go/commit/d99e267b3067af22f4f11acbceabb88410c802ec

**Comment by jinq0123** [comment]
OK now.
